apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/kuda-project/auth
    docker:
      dockerfile: install/auth/Dockerfile
deploy:
  kubectl:
    manifests:
      - install/auth/service.yaml
