release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cli/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/cyrildiagne/kuda/cli/cmd.version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
blobs:
  -
    provider: gs
    bucket: kuda-releases
    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "{{ .Tag }}"
# brews:
#   - # Tap
#     github:
#       owner: cyrildiagne
#       name: kuda-homebrew-tap
#     homepage: "https://github.com/cyrildiagne/kuda"
#     description: "Serverless APIs on remote GPUs."
