apiVersion: v1
kind: Service
metadata:
  name: kuda-mixer-adapter-service
  namespace: istio-system
  labels:
    app: kuda-mixer-adapter
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 44225
      targetPort: 44225
  selector:
    app: kuda-mixer-adapter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuda-mixer-adapter
  namespace: istio-system
  labels:
    app: kuda-mixer-adapter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuda-mixer-adapter
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: kuda-mixer-adapter
          image: gcr.io/kuda-project/kuda-mixer-adapter
          imagePullPolicy: Always
          ports:
            - containerPort: 44225
          volumeMounts:
              - name: secret
                readOnly: true
                mountPath: '/secret'
          env:
            - name: FIRESTORE_CREDENTIALS
              value: /secret/key.json
      volumes:
        - name: secret
          secret:
            secretName: adapter-credentials
