apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/kuda-project/kuda-mixer-adapter
    docker:
      dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - install/adapter.yaml
