apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
  namespace: kuda
spec:
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: gcr.io/kuda-project/api
          volumeMounts:
            - name: secret
              readOnly: true
              mountPath: "/secret"
          env:
            - name: KUDA_GCP_PROJECT
              value: $KUDA_GCP_PROJECT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/key.json
      volumes:
        - name: secret
          secret:
            secretName: api-credentials
