apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/kuda-project/deployer
    docker:
      dockerfile: images/deployer/Dockerfile
deploy:
  kubectl:
    manifests:
      - images/deployer/service-workaround.yaml
