apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/kuda-project/api
      docker:
        dockerfile: install/api/Dockerfile
deploy:
  kubectl:
    manifests:
      - install/api/service-workaround.yaml
