openapi: 3.0.0
info:
  title: Hello GPU
  description: Returns the output of nvidia-smi.
  version: 0.0.1
servers:
  - url: http://hello-gpu.example.com
paths:
  /:
    get:
      responses:
        "200":
          description: The output of nvidia-smi
          content:
            text/plain:
              schema:
                type: string
